 [global.config]
    as = 65000
    router-id = "192.168.1.5"
    port = -1
[[neighbors]]
    [neighbors.config]
        neighbor-address = "192.168.1.4"
        peer-as = 65001
    [neighbors.add-paths.config]
        send-max = 8